[oneplus-rom]
type = drive
scope = drive
token: {"access_token":"ya29.a0AT3oNZ8L2wH5KU9bRkR9Z4r6VzUQ1XDZtN9p_G4Fpmw5TeQnD72xlUFAol18LC7M2wvy4bXH3cFcInDFwSu7xu4PMJDJ9ZyHkI8Z5txePU01VbfXUe5ECtatQMkZfBysPOB7TIE7cwq7YNaRXFby2ezoplHpg261pGsdQ1cn3VT9Wevvs8o796oSa3JqdxM3Y0CjO04aCgYKAegSAQ8SFQHGX2MizS9VMZ2S3yQv3BnyJvSnow0206","token_type":"Bearer","refresh_token":"1//0ge5JVKKlV6sDCgYIARAAGBASNwF-L9IrAmfTdfHSgwG8DFBqlkgnI5ssodUKpWJyudSjAKVQtxNSf0xf0cYq5x4tieWtInFhp5c","expiry":"2026-06-14T17:53:33.7164348+07:00","expires_in":3599}
